@startuml

package "Level 2 data" as L2 {
  (Biodiversity occurrence data) as (CD3)
  (Climate and weather observations) as (CD2)
}

package "Level 4 data" as L4 {
  (Model of arctic fox distribution) as NK 
}

actor "Producer" as Producer
Producer --> (CD2) : Consumes
Producer --> (CD3) : Consumes
Producer --> (NK)  : Produces

@enduml
