@startuml

state "Knowledge generation" as kg {

state Data {
  Data : Satellite data
  Data : Model data
  Data : Time 
  Data : Geographical region
}

state "Processing and interpretation" as PI { 
  PI : Cloud movement over the region
}

state Knowledge {
  Knowledge : Where to likely see northern lights
}

}

Data --> PI
PI --> Knowledge
Knowledge --> Data : Trace and verify

@enduml
