@startuml

state "Knowledge generation" as kg {

state Data {
  Data : Gridded historical weather observations
  Data : Climate model data
}

state "Processing and interpretation" as PI { 
  PI : Bias correction
}

state Knowledge {
  Knowledge :  Dataset of downscaled climate model data (projections)
}

}

Data --> PI
PI --> Knowledge
Knowledge --> Data : Trace and verify

@enduml
