@startuml adc-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
'LAYOUT_LEFT_RIGHT()

Person(consumers, "Data Consumer", "A data consumer from the governance.")

System_Ext(geonorge, "GeoNorge", "Norwegian geodata")

System_Boundary(adc, "Arctic Data Center"){
  ContainerDb(solr, "SOLR", "Metadata store", "Database with harvested metadata.")
  Container(adcweb, "adc.met.no", "Website", "Website for human-machine search (including map search), data collection (basket service) and visualization.")
  Container(csw, "Data catalog interface", "OGC CSW", "")
  Container(oaipmh, "Data catalog interface", "OAI-PMH", "")
}

System(met, "data.met.no", "Data from MET Norway.")
System(nina, "NINA", "Data from NINA.")
System(nilu, "NILU", "Data from NILU.")
System(niva, "NIVA", "Data from NIVA.")
System(mdir, "MDIR", "Data from Miljødirektoratet.")

Rel(consumers, geonorge, "Finds data in")
Rel(consumers, adc, "Finds and accesses data in")
Rel(geonorge, adc, "Harvests metadata", "CSW: ISO19115")
Rel(adc, met, "harvests MMD from", "OGC CSW")
Rel(adc, met, "visualizes data from", "OGC WMS/..")
Rel(adc, met, "accesses data from", "OPeNDAP")
Rel(adc, nina, "harvests EML(?) from", "?")
Rel(adc, nilu, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OAI-PMH")
Rel(adc, niva, "crawls thredds server at", "OPeNDAP")
Rel(adc, mdir, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OGC-CSW")

@enduml
