@startuml met-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

System(adc, "Arctic Data Center", "Central hub for dynamic geodata. The Arctic data center is already a national and international data center that can be reused for S-ENDA purposes.")

Container(catalog, "Metadata services", "", "OGC CSW access point to metadata catalog.")
Container(vis, "Visualization services", "", "E.g., OGC WMS.")
Container(access, "Access services", "Thredds", "NetCDF-CF datasets.")

Rel(adc, catalog, "harvests MMD from", "OGC CSW")
Rel(adc, vis, "visualizes data from", "OGC WMS/..")
Rel(adc, access, "accesses data from", "OPeNDAP")

@enduml
