@startuml met-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
'LAYOUT_LEFT_RIGHT()

Person(consumers, "Data Consumer", "A data consumer from the governance.")

System_Ext(geonorge, "GeoNorge", "Norwegian geodata")

System(adc, "Arctic Data Center", "Central hub for dynamic geodata. The Arctic data center is already a national and international data center that can be reused for S-ENDA purposes.")

System_Boundary(met, "data.met.no"){
  Container(catalog, "Metadata services", "", "OGC CSW access point to metadata catalog.")
  Container(vis, "Visualization services", "", "E.g., OGC WMS.")
  Container(access, "Access services", "Thredds", "NetCDF-CF datasets.")
}

System(nina, "NINA", "Data from NINA.")
System(nilu, "NILU", "Data from NILU.")
System(niva, "NIVA", "Data from NIVA.")
System(mdir, "MDIR", "Data from Miljødirektoratet.")

Rel(consumers, geonorge, "Finds data in")
Rel(consumers, adc, "Finds and accesses data in")
Rel(geonorge, adc, "Harvests metadata", "CSW: ISO19115")
Rel(adc, met, "harvests MMD from", "OGC CSW")
Rel(adc, nina, "harvests EML(?) from", "?")
Rel(adc, nilu, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OAI-PMH")
Rel(adc, niva, "crawls thredds server at", "OPeNDAP")
Rel(adc, mdir, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OGC-CSW")

@enduml
