@startuml national-and-international-context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_LEFT_RIGHT

Person(consumers, "Data Consumer", "A data consumer from the governance.")

System_Ext(geonorge, "GeoNorge", "Norwegian geodata")

System(adc, "Arctic Data Center", "Central hub for dynamic geodata. The Arctic data center is already a national and international data center that can be reused for S-ENDA purposes.")

System(met, "data.met.no", "Data from MET Norway.")
System(nina, "ipt.nina.no", "Data from NINA.")
System(nilu, "NILU", "Data from NILU.")
System(niva, "NIVA", "Data from NIVA.")
System(mdir, "MDIR", "Data from Miljødirektoratet.")

Rel(consumers, geonorge, "Finds data in")
Rel(consumers, adc, "Finds and accesses data in")
Rel(geonorge, adc, "optionally harvests INSPIRE metadata from", "OGC CSW")
Rel(geonorge, met, "harvests INSPIRE metadata from", "OGC CSW")
Rel(geonorge, nilu, "harvests INSPIRE metadata from", "OGC CSW")
Rel(geonorge, mdir, "harvests INSPIRE metadata from", "OGC CSW")
Rel(adc, nilu, "harvests INSPIRE metadata from", "OAI-PMH")
Rel(adc, met, "harvests MMD from", "OGC CSW")
Rel(adc, nina, "harvests EML from", "RSS")
Rel(adc, niva, "crawls thredds server at", "OPeNDAP")
Rel(adc, mdir, "harvests INSPIRE metadata from", "OGC CSW")

@enduml
