@startuml niva-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
'LAYOUT_LEFT_RIGHT()

Person(consumers, "Data Consumer", "A data consumer from the governance.")

System_Ext(geonorge, "GeoNorge", "Norwegian geodata")

System(adc, "Arctic Data Center", "Central hub for dynamic geodata. The Arctic data center is already a national and international data center that can be reused for S-ENDA purposes.")

System(met, "data.met.no", "Data from MET Norway.")
System(nina, "NINA", "Data from NINA.")
System(nilu, "NILU", "Data from NILU.")

System_Boundary(niva, "NIVA"){
  Container(dataset, "NIVA Dataset", "NetCDF-CF", "A NetCDF-CF file with global attributes following the ACDD conventions, and its S-ENDA extension (defined in the Data Management Handbook (DMH)). First prototype dataset: Ocean acidification data (CTD measurements/ferry box system/...).")
  ContainerDb(fileserver, "NIVA storage", "Some file system", "NIVA local storage space.")
  Container(thredds, "NIVA data distribution", "Thredds", "NIVA thredds server used to share NetCDF-CF data through OPeNDAP++.")
}

System(mdir, "MDIR", "Data from Miljødirektoratet.")

Rel(consumers, geonorge, "Finds data in")
Rel(consumers, adc, "Finds and accesses data in")
Rel(geonorge, adc, "Harvests metadata", "CSW: ISO19115")
Rel(adc, met, "harvests MMD from", "OGC CSW")
Rel(adc, nina, "harvests EML(?) from", "?")
Rel(adc, nilu, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OAI-PMH")
Rel(adc, mdir, "harvests Norwegian INSPIRE profile of ISO19115(?) from", "OGC-CSW")

Rel(adc, thredds, "crawls", "OPeNDAP")
Rel(thredds, fileserver, "accesses")
Rel(fileserver, dataset, "stores")



@enduml
