@startuml niva-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

System(adc, "Arctic Data Center", "Central hub for dynamic geodata. The Arctic data center is already a national and international data center that can be reused for S-ENDA purposes.")

Container(dataset, "NIVA Dataset", "NetCDF-CF", "A NetCDF-CF file with global attributes following the ACDD conventions, and its S-ENDA extension (defined in the Data Management Handbook (DMH)). First prototype dataset: Ocean acidification data (CTD measurements/ferry box system/...).")
ContainerDb(fileserver, "NIVA storage", "Some file system", "NIVA local storage space.")
Container(thredds, "NIVA data distribution", "Thredds", "NIVA thredds server used to share NetCDF-CF data through OPeNDAP++.")

Rel(adc, thredds, "crawls", "OPeNDAP")
Rel(thredds, fileserver, "accesses")
Rel(fileserver, dataset, "stores")



@enduml
