@startuml S-ENDA-metadata-service-container-diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Producer", "An advanced consumer of low level data generating new information at a higher level.")
}

System(productionhub, "Production Hubs", "Dataset production hubs provide new datasets (ACDD compliant NetCDF-CF files).")
System(dist_systems, "Data Distribution Systems", "Thredds servers with ACDD compliant NetCDF-CF files.")

Rel(dataprovider, productionhub, "Sets up production of netCDF-CF files with ACDD metadata")

Boundary(consumers, "Data Consumers"){
    Person(advanced, "Advanced")
    Person(intermediate, "Intermediate")
    Person(simple, "Simple")
}

System_Ext(geonorge, "Portals", "External portals harvest metadata on various standards")

Rel(simple, geonorge, "Search portals", "Web-UI/API")
Rel(intermediate, geonorge, "Search portals", "Web-UI/API")
Rel(advanced, geonorge, "Search portals", "Web-UI/API")

System_Boundary(mserviceSystem, "S-ENDA Discovery Metadata Service Node") {

    Container(updater, "Discovery Metadata Catalog Ingestor API", "Python/Flask", "Provides functionality to  create content in metadata stores.")
    Container(metadata_store, "Backup Dataset Discovery Metadata Store", "Git", "MMD discovery and configuration metadata for datasets.")
    Container(csapi, "Dataset Catalog Service API", "pycsw", "CSW endpoint for search and harvesting. Serves INSPIRE, DIF etc. compliant metadata.")
     Container(solr, "Metadata Storage", "solr/or similar", "<b>Optional</b> other metadata storage.")
    Container(web_app, "Web Application", "HTML", "<b>Optional.</b> Provides functionality to register dataset and service metadata, display dataset and service usage statistics, production status, and monitor metadata to display errors and warnings (e.g., about dead links).")

    Rel(updater, csapi, "Create/Delete", "HTTP POST: INSPIRE")
    Rel(updater, metadata_store, "Create/Delete", "git: MMD")
    Rel(updater, solr, "")
}

Rel(geonorge, csapi, "Harvest", "CSW/OAI-PMH")
Rel(advanced, csapi, "Search", "CSW/OpenSearch")
Rel(productionhub, dist_systems, "Store", "ACDD compliant netCDF-CF files")
Rel(productionhub, updater, "Create/Delete", "HTTP POST: MMD")
Rel(dataprovider, web_app, "Check dataset statistics and metadata consistency/status.")

@enduml
