@startuml S-ENDA-metadata-service-container-diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Producer")
}

Boundary(systems, "S-ENDA") {
  System(productionhub, "Production")
  System(dist_systems, "Data Distribution")
  System(monitoring, "Service Monitoring")
  System_Boundary(mserviceSystem, "Discovery Metadata Service") {

    Container(updater, "Discovery Metadata Catalog Ingestor API", "Python/Flask", "Provides functionality to  create content in metadata stores.")
    Container(validator, "MMD validator", "Python", "Validator for MMD xml files.")
    Container(metadata_store, "Backup Dataset Discovery Metadata Store", "File", "Backup MMD storage. Committed to git on regular intervals.")
    Container(csapi, "Dataset Catalog Service API", "pycsw", "CSW endpoint for search and harvesting. Serves INSPIRE, DIF etc. compliant metadata.")
    Container(solr, "Metadata Storage", "Solr", "Metadata storage for Drupal websites.")
    Container(mms, "Messaging", "MMS", "<b>Optional</b> message production.")
    Container(web_app, "Web Application", "HTML", "<b>Optional.</b> Provides functionality to register dataset and service metadata, display dataset and service usage statistics, production status, and monitor metadata to display errors and warnings (e.g., about dead links).")

    Rel(updater, validator, "Validate", "MMD")
    Rel(updater, csapi, "Create/Update/Delete", "HTTP POST: INSPIRE")
    Rel(updater, metadata_store, "Create/Update/Delete", "MMD")
    Rel(updater, solr, "Create/Update/Delete", "MMD")
    Rel(updater, mms, "Create/Update/Delete", "MMD")
  }
}


Boundary(consumers, "Data Consumers"){
  Person(advanced, "Advanced")
  Person(intermediate, "Intermediate")
  Person(simple, "Simple")
}

System_Ext(portals, "Portals", "External portals harvest metadata on various standards")
System_Ext(apps, "Web/mobile apps", "External apps present data in customized ways.")

Rel(dataprovider, productionhub, "Sets up data production")
Rel(productionhub, mms, "Listen for Create/Update/Delete", "MMD")

Rel(simple, portals, "Search portals", "Web-UI/API")
Rel(intermediate, portals, "Search portals", "Web-UI/API")
Rel(advanced, portals, "Search portals", "Web-UI/API")

Rel(apps, csapi, "Search", "CSW")
Rel(apps, dist_systems, "Stream data")
Rel(simple, apps, "Navigates to app", "Web/mobile UI")

Rel(portals, csapi, "Harvest", "CSW/OAI-PMH")
Rel(portals, solr, "Harvest", "CSW/OAI-PMH")
Rel(advanced, csapi, "Search", "CSW/OpenSearch")
Rel(productionhub, dist_systems, "Store", "ACDD compliant netCDF-CF files")
Rel(productionhub, updater, "Validate/Create/Update/Delete", "HTTP POST: MMD")
Rel(dataprovider, web_app, "Check dataset statistics and metadata consistency/status.")

@enduml
