@startuml S-ENDA-production-container-diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Producer")
}

Boundary(systems, "S-ENDA") {
  System_Boundary(productionhub, "Production"){
    Container(listen_update, "Update listener", "", "Listens for metadata updates, updates metadata in datafiles on behalf of authenticated user.")
    Container(listen_delete, "Deletion listener", "", "Listens for metadata, and deletes files on behalf of authenticated user.")
    Container(listen_start, "Production listener", "", "Listens for metadata, and starts new processing on behalf of authenticated user.")
    Container(job, "Production job", "SMS/PPI", "Production Script")

    Rel(listen_start, job, "Start job")
  }
  System(monitoring, "Service Monitoring")
  System(mserviceSystem, "Discovery Metadata Service")
  System(datadist, "Data Distribution")
}

Boundary(consumers, "Data Consumers"){
  Person(advanced, "Advanced")
  Person(intermediate, "Intermediate")
  Person(simple, "Simple")
}

System_Ext(portals, "Portals", "External portals harvest metadata on various standards")
System_Ext(apps, "Web/mobile apps", "External apps present data in customized ways.")

Rel(listen_update, mserviceSystem, "Listen update")
Rel(listen_delete, mserviceSystem, "Listen delete")
Rel(listen_start, mserviceSystem, "Listen create")

Rel(dataprovider, job, "Sets up data production")

Rel(simple, portals, "Search portals", "Web-UI/API")
Rel(intermediate, portals, "Search portals", "Web-UI/API")
Rel(advanced, portals, "Search portals", "Web-UI/API")

Rel(apps, mserviceSystem, "Search", "CSW")
Rel(apps, datadist, "Stream", "WMS/WMTS/etc.")
Rel(simple, apps, "Navigates to app", "Web/mobile UI")

Rel(portals, mserviceSystem, "Harvest", "CSW/OAI-PMH")
Rel(advanced, mserviceSystem, "Search", "CSW/OpenSearch")
Rel(job, datadist, "Store")
Rel(job, mserviceSystem, "Create/Update/Delete", "HTTP POST: MMD")

Rel(portals, datadist, "Stream", "OPeNDAP/WMS/WMTS/etc.")
Rel(advanced, datadist, "Stream", "OPeNDAP")

@enduml
