@startuml S-ENDA-data-distribution-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

Person(dataproducer, "Dataset Producer")
Person(consumers, "Data Consumer", "A data consumer can be a human (advanced, intermediate or simple users) or a machine (e.g., a mobile app or a data portal). Simple and intermediate users search, inspect, and access data via an external interface (e.g., a mobile app or data portal). Advanced users acess the search, visualization, and distribution services directly. Open licenses and well documented data following international standards enable Interoperability and Reusability.")

System(productionhub, "Production", "Automated system for data production. ECFlow, PPI, SMS, etc.")
SystemDb(lustre, "Data storage", "Lustre file system.")
System_Boundary(datadist, "Data Distribution Services") {
  Container(access, "Data Access Service", "OPeNDAP", "OPeNDAP service supported by, e.g., thredds or hyrax, to provide actual data access.")
}

Rel(dataproducer, productionhub, "Sets up production of netCDF-CF files with ACDD metadata")

Rel_U(consumers, access, "Stream", "OPeNDAP")
Rel(productionhub, lustre, "Store")
Rel(access, lustre, "Access")

SHOW_LEGEND()

@enduml
