@startuml S-ENDA-production-container-diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Producer")
}

Boundary(systems, "S-ENDA") {
  System_Boundary(productionhub, "Production"){
    Container(listen_update, "Production listener", "", "Listens for metadata updates, updates metdata in datafiles on behalf of authenticated user.")
    Container(listen_delete, "Production listener", "", "Listens for metadata, and deletes files on behalf of authenticated user.")
    Container(listen_start, "Production listener", "", "Listens for metadata, and starts new processing on behalf of authenticated user.")
    Container(job, "Job", "SMS/PPI", "Production Script")

    Container(mmd, "py-mmd-tools", "MMD production")
    Container(mms, "MMS", "Message production")

    Rel(listen_update, mms, "")
    Rel(listen_delete, mms, "")
    Rel(listen_start, mms, "")
    Rel(listen_start, job, "Start job")
  }
  System(monitoring, "Service Monitoring")
  System(mserviceSystem, "Discovery Metadata Service")
  System(datadist, "Data Distribution")
}

Boundary(consumers, "Data Consumers"){
  Person(advanced, "Advanced")
  Person(intermediate, "Intermediate")
  Person(simple, "Simple")
}

System_Ext(portals, "Portals", "External portals harvest metadata on various standards")
System_Ext(apps, "Web/mobile apps", "External apps present data in customized ways.")

Rel(dataprovider, job, "Sets up production of netCDF-CF files with ACDD metadata")

Rel(simple, portals, "Search portals", "Web-UI/API")
Rel(intermediate, portals, "Search portals", "Web-UI/API")
Rel(advanced, portals, "Search portals", "Web-UI/API")

Rel(apps, mserviceSystem, "Search", "CSW")
Rel(apps, datadist, "Stream", "WMS/WMTS/etc.")
Rel(simple, apps, "Navigates to app", "Web/mobile UI")

Rel(portals, mserviceSystem, "Harvest", "CSW/OAI-PMH")
Rel(advanced, mserviceSystem, "Search", "CSW/OpenSearch")
Rel(job, datadist, "Store")
Rel(job, mserviceSystem, "Create/Update/Delete", "HTTP POST: MMD")
Rel(dataprovider, mserviceSystem, "Check dataset statistics and metadata consistency/status.")

Rel(portals, datadist, "Stream", "OPeNDAP/WMS/WMTS/etc.")
Rel(advanced, datadist, "Stream", "OPeNDAP")

Rel(job, mmd, "Generate MMD file")
Rel(job, mserviceSystem,"Register MMD file","HTTPS")
Rel(job, mms,"Register MMS event","HTTPS")

@enduml
