@startuml S-ENDA
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

System_Ext(geonorge, "geonorge.no")

Boundary(senda, "S-ENDA") {
    
Person(dataprovider, "Data Provider")
Person(datacurator, "Data curator")

System(pycswThredds, "pyCSW Catalogue for Thredds")
System(thredds, "Thredds", "thredds")
System(productionhub, "Production hub")
System(pycswCurator, "pyCSW Curated catalogue")
System(geomonitor, "Metadata monitor")

System(curationeditor, "Curation editor", "Dashboard/UI or pygeometa yaml")

Rel(geomonitor, pycswCurator, "Checks for dead links")
Rel(dataprovider, productionhub, "Sets up data production with metadata in ACDD")
Rel(productionhub, thredds, "Configures access to data")
Rel(pycswThredds, thredds, "Harvests metadata")
Rel(datacurator, curationeditor, "Configures data series and collections")
Rel(curationeditor, pycswCurator, "Populates catalogue")
Rel(pycswCurator, pycswThredds, "Harvests metadata", "")
}

Rel(geonorge, pycswCurator, "Harvests", "ISO19115 or GeoDCAT-AP via CSW")

@enduml
