@startuml

package "Level 2 data" as L2 {
  (Aggregated time series\nSource:) as (CD2)
}
package "Level 3 data" as L3 {
  (Gridded historical weather observations\nSource:) as (CD3)
}

package "Level 4 data" as L4 {
  (Climate model data\nSource:) as (CD4)
  (Projections for Norway) as NK 
}

actor "Producer" as Producer

Producer --> (CD2) : Produces and Consumes
Producer --> (CD3) : Consumes
Producer --> (CD4) : Consumes
Producer --> (NK)  : Produces

@enduml
