@startuml S-ENDA context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_LEFT_RIGHT

Boundary(producers, "Producers") {
    Person(developer, "Service Provider")
    Person(dataprovider, "Data Provider")
}

Boundary(users, "Users") {
    Person(professional, "Advanced user")
    Person(user, "General user")
}

System(senda, "S-ENDA Find")

System_Boundary(portals, "Portals") {
    System_Ext(geonorge, "GeoNorge")
    System_Ext(searchengine, "Web Search Engines")
    System_Ext(datacite, "DataCite")
    System_Ext(adc, "ADC")
    System_Ext(europeandataportal, "European Data Portal")
}

Rel(professional, portals, "Searches", "API")
Rel(users, portals, "Searches", "Web UI")

Rel(developer, senda, "Registers service", "API/Web UI")
Rel(geonorge, senda, "Harvests metadata", "CSW")
Rel(adc, senda, "Harvests metadata", "CSW")

Rel(dataprovider, senda, "Registers dataset", "API/Web UI")

Rel(senda, dataprovider, "Gets feedback", "Validation/Monitoring/user questions")
Rel(senda, developer, "Gets feedback", "Validation/Monitoring/user questions")

Rel(senda, datacite, "Registers DOI", "API")

Rel(searchengine, geonorge, "Harvests metadata", "DCAT")
Rel(europeandataportal, geonorge, "Harvests metadata", "DCAT")

@enduml
