@startuml S-ENDA context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_LEFT_RIGHT

System_Boundary(senda, "S-ENDA Metadata Service with Central Catalogue") {
    System(sendafind1, "S-ENDA Metadata Service Node 1")
    System(sendafind2, "S-ENDA Metadata Service Node 2")
    System(sendafindn, "S-ENDA Metadata Service Node n")
    System(senda_central, "S-ENDA Central Catalogue")
}

Person(users, "Users")
System_Ext(portals, "Portals")

Rel(senda_central, sendafind1, "Harvests metadata", "CSW")
Rel(senda_central, sendafind2, "Harvests metadata", "CSW")
Rel(senda_central, sendafindn, "Harvests metadata", "CSW")

Rel(users, senda_central, "Searches", "OpenSearch, CSW")
Rel(portals, senda_central, "Harvests", "CSW")

@enduml
