@startuml S-ENDA context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

LAYOUT_LEFT_RIGHT

System_Ext(geonorge, "GeoNorge", "description")


System_Boundary(senda, "S-ENDA Find") {

Container(eventengine, "Event Engine", "")

Container(data_store, "Metadata Store", "mocked as in-memory structure in Dynamic Geo-Assets container")
Container(geoasset_api, "Dynamic Geo-Assets API", "custom written API for Metadata store")


Container(pycswapi, "CSW API", "pyCSW + custom adapter for MMD")

Rel(pycswapi, geoasset_api, "Reads metadata updates", "REST (MMD)")
Rel(geoasset_api, data_store, "Create/Read/Update/Delete metadata in the metadata store")
Rel(geoasset_api, eventengine, "Listens in order to get last updated info", "CloudEvents")
}

Rel(geonorge, pycswapi, "Harvests metadata", "CSW")


@enduml
