@startuml S-ENDA harvest context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_LEFT_RIGHT

System_Boundary(portals, "Portals"){
   System_Ext(edp, "European Data Portal")
   System_Ext(searchengine, "Web Search Engines")
   System_Ext(inspire, "Inspire Geoportal")
   System_Ext(datanorge, "Data Norge")
   System_Ext(geonorge, "GeoNorge")
   System_Ext(adc, "ADC")
}

'Not sure about the following...
System_Boundary(senda, "S-ENDA Metadata Service"){
   System(sendafind, "S-ENDA Metadata Service Nodes")
}

Rel(adc, senda, "Harvests metadata", "CSW: MMD")
Rel(geonorge, senda, "Harvests metadata", "CSW: ISO19115")
Rel(searchengine, senda, "Harvests metadata", "?: DCAT")
Rel(inspire, geonorge, "Harvests metadata", "?: ?")
Rel(datanorge, senda, "Harvests metadata", "?: DCAT")
Rel(edp, datanorge, "Harvests metadata", "?: ?")

@enduml
