@startuml

state "Knowledge generation" as kg {

state Data {
  Data : Gridded historical weather observations
  Data : Climate model data
}

state Information { 
  Information : Bias correction
}

state Knowledge {
  Knowledge :  Downscaled climate model data
}

state "Tailored knowledge" as tk {
  tk : Changes in the average number of days with snow on the ground
}
}

Data --> Information
Information --> Knowledge
Knowledge --> tk
tk --> Data : Trace and verify

@enduml
