@startuml

state "Knowledge generation" as kg {
state Data {
  Data : Mercury pressure
  Data : Wind speed and direction
}

state "Processing and interpretation" as PI { 
  PI : Temperature changes
  PI : Wind changes
}

state Knowledge {
  Knowledge :  It will most likely be raining
}

}

Data --> PI
PI --> Knowledge
Knowledge --> Data : Trace and verify

@enduml
