 @startuml S-ENDA provider context
   !includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

   LAYOUT_LEFT_RIGHT

   System(dgaAPI, "S-ENDA Metadata Service Node")

   Boundary(providers, "Providers") {
      Person(developer, "Service Provider (SP)")
      Person(dataprovider, "Data Provider (DP)")
   }

   'System_Ext(doiregistrar, "DOI Registrar")

   'Rel(dataprovider, doiregistrar, "Alt. 1: DP registers DOI")
   'Rel(dgaAPI, doiregistrar, "Alt. 2: DGA API registers DOI", "DataCite API")
   Rel(dataprovider, dgaAPI, "DP registers dataset", "API/Web UI")
   Rel(dgaAPI, dataprovider, "DGA API gives feedback", "Validation/Monitoring/user questions")

   Rel(developer, dgaAPI, "SP registers service", "API/Web UI")
   Rel(dgaAPI, developer, "DGA API gives feedback", "Validation/Monitoring/user questions")

   @enduml