@startuml S-ENDA pyCSW harvesting diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_LEFT_RIGHT

Container(metadata_store, "Metadata Store", "GeoDCAT-AP")
Container(pycsw, "Catalog Service API", "pycsw")

Rel(pycsw, metadata_store, "Harvest", "ISO19139")

@enduml
