@startuml S-ENDA-data-distribution-container-diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

'LAYOUT_LEFT_RIGHT
LAYOUT_TOP_DOWN

Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Provider")
    Person(datacurator, "Data curator")
    Person(serviceprovider, "Service Provider")
}

System(productionhub, "Production Hubs", "Dataset production hubs provide new datasets (ACDD compliant NetCDF-CF files).")
System(mserviceSystem, "S-ENDA Discovery Metadata Service")
System_Boundary(dist_systems, "Data Distribution Systems") {
    Container(zarr, "S3/Zarr", "S3/Zarr", "Provides data from S3/Zarr.")
    Container(opendap, "thredds", "OPeNDAP", "Provides data.")
    Container(wms, "thredds", "WMS", "Provides data visualization.")
}


Boundary(consumers, "Data Consumers"){
    Person(advanced, "Advanced")
    Person(intermediate, "Intermediate")
    Person(simple, "Simple")
}

System_Ext(geonorge, "Portals", "External portals harvest metadata on various standards")

Rel(simple, geonorge, "Search portals", "Web-UI/API")
Rel(intermediate, geonorge, "Search portals", "Web-UI/API")
Rel(advanced, geonorge, "Search portals", "Web-UI/API")

Rel(dataprovider, productionhub, "Sets up production of netCDF-CF files with ACDD metadata")

Rel(geonorge, mserviceSystem, "Harvest", "CSW")
Rel(advanced, mserviceSystem, "Search", "CSW OpenSearch")
Rel(mserviceSystem, dist_systems, "Get discovery metadata", "OPeNDAP: ACDD/CF")
Rel(productionhub, dist_systems, "Store", "ACDD compliant netCDF-CF files")
Rel(mserviceSystem, productionhub, "Listens in order to get last updated info", "CloudEvents")
Rel(mserviceSystem, productionhub, "Harvest metrics")
Rel(mserviceSystem, dist_systems, "Harvest metrics")
Rel(providers, mserviceSystem, "Register/configure/check.")

@enduml
