@startuml S-ENDA metadata service C4 context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
   
LAYOUT_TOP_DOWN

Boundary(consumers, "Data Consumers"){
    Person(advanced, "Advanced")
    Person(intermediate, "Intermediate")
    Person(simple, "Simple")
}
    
Boundary(providers, "Providers") {
    Person(dataprovider, "Dataset Producer")
    Person(datacurator, "Data curator")
    Person(serviceprovider, "Service Provider")
}

Boundary(systems, "S-ENDA systems") {
    System(senda, 'S-ENDA Discovery Metadata Service')
    System(productionhub, "Production", "Dataset production hubs provide new datasets (ACDD compliant NetCDF-CF files).")
    System(dist_systems, "Data Distribution", "Thredds servers with ACDD compliant NetCDF-CF files.")
}

System_Ext(portals, "Portals", "External portals harvest metadata on various standards")

Rel(advanced, portals, "Search portals", "Web-UI/API")
Rel(intermediate, portals, "Search portals", "Web-UI/API")
Rel(simple, portals, "Search portals", "Web-UI/API")

Rel(advanced, senda, "Search", "CSW OpenSearch: ISO19115/DCAT/MMD")
Rel(portals, senda, "Harvest metadata", "CSW: ISO19139")

Rel(providers, senda, "Register metadata")
Rel(providers, senda, "Check usage statistics and metadata consistency/status.")

Rel(dataprovider, productionhub, "Sets up production of netCDF-CF files with ACDD metadata")
Rel(productionhub, dist_systems, "Store", "ACDD compliant netCDF-CF files")
Rel(senda, productionhub, "Listen in order to get last updated info, and harvest metrics")
Rel(senda, dist_systems, "Get metadata and metrics")

@enduml
