@startuml S-ENDA context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_LEFT_RIGHT

Person(researcher, "Researcher")

System_Ext(searchengine, "Search Engine", "Google")

Rel(researcher, searchengine, "Searches for: observed and forecasted temperature Longyearbyen")
Rel(searchengine, researcher, "Returns result with link to dataset description and download link")


@enduml
